--INSERT INTO Authors (name) VALUES ('F. Scott Fitzgerald');
--INSERT INTO Books (title, author_id, unit_price, stock_quantity, image_url) VALUES ('The Great Gatsby', 1, 10.99, 20, 'test');



INSERT INTO Authors (name) VALUES ('J.K. Rowling');
INSERT INTO Authors (name) VALUES ('J.R.R. Tolkien');
INSERT INTO Authors (name) VALUES ('Suzanne Collins');
INSERT INTO Authors (name) VALUES ('Dan Brown');
INSERT INTO Authors (name) VALUES ('J.D. Salinger');
INSERT INTO Authors (name) VALUES ('Harper Lee');
INSERT INTO Authors (name) VALUES ('George Orwell');
INSERT INTO Authors (name) VALUES ('Jane Austen');
INSERT INTO Authors (name) VALUES ('F. Scott Fitzgerald');
INSERT INTO Authors (name) VALUES ('Herman Melville');
INSERT INTO Authors (name) VALUES ('Lewis Carroll');
INSERT INTO Authors (name) VALUES ('Mark Twain');
INSERT INTO Authors (name) VALUES ('Homer');
INSERT INTO Authors (name) VALUES ('Leo Tolstoy');
INSERT INTO Authors (name) VALUES ('Mary Shelley');
INSERT INTO Authors (name) VALUES ('Bram Stoker');
INSERT INTO Authors (name) VALUES ('Oscar Wilde');
INSERT INTO Authors (name) VALUES ('Gabriel García Márquez');
INSERT INTO Authors (name) VALUES ('John Steinbeck');
INSERT INTO Authors (name) VALUES ('Stephen King');
INSERT INTO Authors (name) VALUES ('Aldous Huxley');
INSERT INTO Authors (name) VALUES ('Charles Dickens');
INSERT INTO Authors (name) VALUES ('Victor Hugo');
INSERT INTO Authors (name) VALUES ('Virginia Woolf');
INSERT INTO Authors (name) VALUES ('Ernest Hemingway');
INSERT INTO Authors (name) VALUES ('Fyodor Dostoevsky');
INSERT INTO Authors (name) VALUES ('George Eliot');
INSERT INTO Authors (name) VALUES ('Miguel de Cervantes');
INSERT INTO Authors (name) VALUES ('H.G. Wells');
INSERT INTO Authors (name) VALUES ('Emily Brontë');
INSERT INTO Authors (name) VALUES ('Charlotte Brontë');
INSERT INTO Authors (name) VALUES ('Joseph Heller');
INSERT INTO Authors (name) VALUES ('Alexandre Dumas');
INSERT INTO Authors (name) VALUES ('Anthony Burgess');
INSERT INTO Authors (name) VALUES ('Toni Morrison');
INSERT INTO Authors (name) VALUES ('Arthur Conan Doyle');
INSERT INTO Authors (name) VALUES ('Jack London');
INSERT INTO Authors (name) VALUES ('Nathaniel Hawthorne');
INSERT INTO Authors (name) VALUES ('Kenneth Grahame');
INSERT INTO Authors (name) VALUES ('Alexandre Dumas');
INSERT INTO Authors (name) VALUES ('Kenneth Grahame');
INSERT INTO Authors (name) VALUES ('H.G. Wells');
INSERT INTO Authors (name) VALUES ('Mary Shelley');
INSERT INTO Authors (name) VALUES ('Herman Melville');
INSERT INTO Authors (name) VALUES ('Emily Brontë');
INSERT INTO Authors (name) VALUES ('Charlotte Brontë');
INSERT INTO Authors (name) VALUES ('Jack London');

INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('Harry Potter and the Sorcerer''s Stone', 1, 19.99, 100, 'Fantasy', 'https://covers.openlibrary.org/b/olid/OL26311688M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Hobbit', 2, 14.99, 90, 'Fantasy', 'https://covers.openlibrary.org/b/olid/OL5334903M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Lord of the Rings', 2, 29.99, 120, 'Fantasy', 'https://covers.openlibrary.org/b/olid/OL4720931M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Hunger Games', 3, 12.99, 80, 'Science Fiction', 'https://covers.openlibrary.org/b/olid/OL7915666M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Da Vinci Code', 4, 15.99, 110, 'Mystery', 'https://covers.openlibrary.org/b/olid/OL24218286M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Catcher in the Rye', 5, 9.99, 70, 'Classic', 'https://covers.openlibrary.org/b/olid/OL23280426M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('To Kill a Mockingbird', 6, 11.99, 85, 'Classic', 'https://covers.openlibrary.org/b/olid/OL24237920M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('1984', 7, 10.99, 95, 'Dystopian', 'https://covers.openlibrary.org/b/olid/OL2715224M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('Pride and Prejudice', 8, 8.99, 75, 'Romance', 'https://covers.openlibrary.org/b/olid/OL24225895M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Great Gatsby', 9, 7.99, 65, 'Classic', 'https://covers.openlibrary.org/b/olid/OL2737262M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('Moby Dick', 10, 13.99, 105, 'Adventure', 'https://covers.openlibrary.org/b/olid/OL24194991M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('Alice''s Adventures in Wonderland', 11, 6.99, 55, 'Fantasy', 'https://covers.openlibrary.org/b/olid/OL14307254M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('Adventures of Huckleberry Finn', 12, 9.99, 85, 'Adventure', 'https://covers.openlibrary.org/b/olid/OL2044307M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Odyssey', 13, 11.99, 95, 'Epic', 'https://covers.openlibrary.org/b/olid/OL26455285M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('War and Peace', 14, 21.99, 125, 'Historical Fiction', 'https://covers.openlibrary.org/b/olid/OL1859518M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('Don Quixote', 15, 17.99, 115, 'Adventure', 'https://covers.openlibrary.org/b/olid/OL18222850M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Old Man and the Sea', 16, 8.99, 60, 'Adventure', 'https://covers.openlibrary.org/b/olid/OL7299082M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('Crime and Punishment', 17, 12.99, 95, 'Psychological Fiction', 'https://covers.openlibrary.org/b/olid/OL23279740M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('Frankenstein', 18, 10.99, 80, 'Gothic Fiction', 'https://covers.openlibrary.org/b/olid/OL19617669M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('Dracula', 19, 9.99, 70, 'Gothic Horror', 'https://covers.openlibrary.org/b/olid/OL5275157M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Picture of Dorian Gray', 20, 7.99, 55, 'Gothic', 'https://covers.openlibrary.org/b/olid/OL18022116M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('One Hundred Years of Solitude', 21, 11.99, 90, 'Magic Realism', 'https://covers.openlibrary.org/b/olid/OL24937185M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('Of Mice and Men', 22, 6.99, 65, 'Tragedy', 'https://covers.openlibrary.org/b/olid/OL1021236M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Shining', 23, 8.99, 75, 'Horror', 'https://covers.openlibrary.org/b/olid/OL1104486M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('Brave New World', 24, 9.99, 80, 'Dystopian', 'https://covers.openlibrary.org/b/olid/OL23280061M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('Great Expectations', 25, 7.99, 60, 'Classic', 'https://covers.openlibrary.org/b/olid/OL3219966M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('Les Misérables', 26, 12.99, 100, 'Historical Fiction', 'https://covers.openlibrary.org/b/olid/OL24404937M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('Mrs. Dalloway', 27, 6.99, 55, 'Modernist Literature', 'https://covers.openlibrary.org/b/olid/OL24237836M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Time Machine', 28, 9.99, 70, 'Science Fiction', 'https://covers.openlibrary.org/b/olid/OL23962351M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('Wuthering Heights', 29, 8.99, 65, 'Gothic Fiction', 'https://covers.openlibrary.org/b/olid/OL24227080M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Adventures of Tom Sawyer', 12, 7.99, 60, 'Adventure', 'https://covers.openlibrary.org/b/olid/OL3311271M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('Catch-22', 30, 10.99, 85, 'Satire', 'https://covers.openlibrary.org/b/olid/OL2637120M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('East of Eden', 31, 11.99, 95, 'Family Saga', 'https://covers.openlibrary.org/b/olid/OL24228935M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Count of Monte Cristo', 32, 13.99, 105, 'Adventure', 'https://covers.openlibrary.org/b/olid/OL24229541M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('A Tale of Two Cities', 33, 8.99, 75, 'Historical Fiction', 'https://covers.openlibrary.org/b/olid/OL2335155M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('A Clockwork Orange', 34, 9.99, 80, 'Dystopian', 'https://covers.openlibrary.org/b/olid/OL24980986M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('Beloved', 35, 10.99, 85, 'Historical Fiction', 'https://covers.openlibrary.org/b/olid/OL25300272M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Adventures of Sherlock Holmes', 36, 7.99, 65, 'Mystery', 'https://covers.openlibrary.org/b/olid/OL24238067M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('White Fang', 37, 6.99, 55, 'Adventure', 'https://covers.openlibrary.org/b/olid/OL396012M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Scarlet Letter', 38, 8.99, 70, 'Romance', 'https://covers.openlibrary.org/b/olid/OL690553M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Three Musketeers', 39, 11.99, 90, 'Historical Adventure', 'https://covers.openlibrary.org/b/olid/OL13583998M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('Oliver Twist', 40, 9.99, 75, 'Classic', 'https://covers.openlibrary.org/b/olid/OL26340760M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('A Christmas Carol', 40, 6.99, 60, 'Classic', 'https://covers.openlibrary.org/b/olid/OL28896984M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('A Clockwork Orange', 41, 12.99, 100, 'Science Fiction', 'https://covers.openlibrary.org/b/olid/OL2747241M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Wind in the Willows', 42, 8.99, 70, 'Fantasy', 'https://covers.openlibrary.org/b/olid/OL6942864M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Adventures of Tom Sawyer', 43, 9.99, 80, 'Adventure', 'https://covers.openlibrary.org/b/olid/OL6917345M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('Treasure Island', 44, 7.99, 65, 'Adventure', 'https://covers.openlibrary.org/b/olid/OL7269784M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Strange Case of Dr. Jekyll and Mr. Hyde', 45, 6.99, 55, 'Gothic Fiction', 'https://covers.openlibrary.org/b/olid/OL2742352M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Secret Garden', 46, 8.99, 70, 'Children''s Literature', 'https://covers.openlibrary.org/b/olid/OL13432571M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Call of the Wild', 47, 9.99, 80, 'Adventure', 'https://covers.openlibrary.org/b/olid/OL394339M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Adventures of Sherlock Holmes', 36, 7.99, 65, 'Mystery', 'https://covers.openlibrary.org/b/olid/OL24238067M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('White Fang', 37, 6.99, 55, 'Adventure', 'https://covers.openlibrary.org/b/olid/OL396012M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Scarlet Letter', 38, 8.99, 70, 'Romance', 'https://covers.openlibrary.org/b/olid/OL690553M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('The Three Musketeers', 39, 11.99, 90, 'Historical Adventure', 'https://covers.openlibrary.org/b/olid/OL13583998M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('Oliver Twist', 40, 9.99, 75, 'Classic', 'https://covers.openlibrary.org/b/olid/OL26340760M-L.jpg');
INSERT INTO Books (title, author_id, unit_price, stock_quantity, genres, image_url) VALUES ('A Christmas Carol', 40, 6.99, 60, 'Classic', 'https://covers.openlibrary.org/b/olid/OL28896984M-L.jpg');


INSERT INTO Users (user_name, first_name, last_name, email_address) VALUES ('Admin','Admin','Admin', 'sample@test.com');
