--Initial data loading
INSERT INTO Authors (name) VALUES ('J.K. Rowling');
INSERT INTO Authors (name) VALUES ('J.R.R. Tolkien');
INSERT INTO Authors (name) VALUES ('Suzanne Collins');
INSERT INTO Authors (name) VALUES ('Dan Brown');
INSERT INTO Authors (name) VALUES ('J.D. Salinger');
INSERT INTO Authors (name) VALUES ('Harper Lee');
INSERT INTO Authors (name) VALUES ('George Orwell');
INSERT INTO Authors (name) VALUES ('Jane Austen');
INSERT INTO Authors (name) VALUES ('F. Scott Fitzgerald');
INSERT INTO Authors (name) VALUES ('Herman Melville');
INSERT INTO Authors (name) VALUES ('Lewis Carroll');
INSERT INTO Authors (name) VALUES ('Mark Twain');
INSERT INTO Authors (name) VALUES ('Homer');
INSERT INTO Authors (name) VALUES ('Leo Tolstoy');
INSERT INTO Authors (name) VALUES ('Mary Shelley');
INSERT INTO Authors (name) VALUES ('Bram Stoker');
INSERT INTO Authors (name) VALUES ('Oscar Wilde');
INSERT INTO Authors (name) VALUES ('Gabriel García Márquez');
INSERT INTO Authors (name) VALUES ('John Steinbeck');
INSERT INTO Authors (name) VALUES ('Stephen King');
INSERT INTO Authors (name) VALUES ('Aldous Huxley');
INSERT INTO Authors (name) VALUES ('Charles Dickens');
INSERT INTO Authors (name) VALUES ('Victor Hugo');
INSERT INTO Authors (name) VALUES ('Virginia Woolf');
INSERT INTO Authors (name) VALUES ('Ernest Hemingway');
INSERT INTO Authors (name) VALUES ('Fyodor Dostoevsky');
INSERT INTO Authors (name) VALUES ('George Eliot');
INSERT INTO Authors (name) VALUES ('Miguel de Cervantes');
INSERT INTO Authors (name) VALUES ('H.G. Wells');
INSERT INTO Authors (name) VALUES ('Emily Brontë');
INSERT INTO Authors (name) VALUES ('Charlotte Brontë');
INSERT INTO Authors (name) VALUES ('Joseph Heller');
INSERT INTO Authors (name) VALUES ('Alexandre Dumas');
INSERT INTO Authors (name) VALUES ('Anthony Burgess');
INSERT INTO Authors (name) VALUES ('Toni Morrison');
INSERT INTO Authors (name) VALUES ('Arthur Conan Doyle');
INSERT INTO Authors (name) VALUES ('Jack London');
INSERT INTO Authors (name) VALUES ('Nathaniel Hawthorne');
INSERT INTO Authors (name) VALUES ('Kenneth Grahame');
INSERT INTO Authors (name) VALUES ('Alexandre Dumas');
INSERT INTO Authors (name) VALUES ('Kenneth Grahame');
INSERT INTO Authors (name) VALUES ('H.G. Wells');
INSERT INTO Authors (name) VALUES ('Mary Shelley');
INSERT INTO Authors (name) VALUES ('Herman Melville');
INSERT INTO Authors (name) VALUES ('Emily Brontë');
INSERT INTO Authors (name) VALUES ('Charlotte Brontë');
INSERT INTO Authors (name) VALUES ('Jack London');

INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('Harry Potter and the Sorcerer''s Stone', 1, 19.99, 'Fantasy');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('The Hobbit', 2, 14.99, 'Fantasy');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('The Lord of the Rings', 2, 29.99, 'Fantasy');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('The Hunger Games', 3, 12.99, 'Science Fiction');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('The Da Vinci Code', 4, 15.99, 'Mystery');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('The Catcher in the Rye', 5, 9.99, 'Classic');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('To Kill a Mockingbird', 6, 11.99, 'Classic');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('1984', 7, 10.99, 'Dystopian');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('Pride and Prejudice', 8, 8.99, 'Romance');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('The Great Gatsby', 9, 7.99, 'Classic');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('Moby Dick', 10, 13.99, 'Adventure');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('Alice''s Adventures in Wonderland', 11, 6.99, 'Fantasy');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('Adventures of Huckleberry Finn', 12, 9.99, 'Adventure');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('The Odyssey', 13, 11.99, 'Epic');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('War and Peace', 14, 21.99, 'Historical Fiction');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('Don Quixote', 15, 17.99, 'Adventure');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('The Old Man and the Sea', 16, 8.99, 'Adventure');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('Crime and Punishment', 17, 12.99, 'Psychological Fiction');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('Frankenstein', 18, 10.99, 'Gothic Fiction');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('Dracula', 19, 9.99, 'Gothic Horror');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('The Picture of Dorian Gray', 20, 7.99, 'Gothic');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('One Hundred Years of Solitude', 21, 11.99, 'Magic Realism');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('Of Mice and Men', 22, 6.99, 'Tragedy');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('The Shining', 23, 8.99, 'Horror');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('Brave New World', 24, 9.99, 'Dystopian');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('Great Expectations', 25, 7.99, 'Classic');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('Les Misérables', 26, 12.99, 'Historical Fiction');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('Mrs. Dalloway', 27, 6.99, 'Modernist Literature');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('The Time Machine', 28, 9.99, 'Science Fiction');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('Wuthering Heights', 29, 8.99, 'Gothic Fiction');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('The Adventures of Tom Sawyer', 12, 7.99, 'Adventure');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('Catch-22', 30, 10.99, 'Satire');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('East of Eden', 31, 11.99, 'Family Saga');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('The Count of Monte Cristo', 32, 13.99, 'Adventure');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('A Tale of Two Cities', 33, 8.99, 'Historical Fiction');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('A Clockwork Orange', 34, 9.99, 'Dystopian');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('Beloved', 35, 10.99, 'Historical Fiction');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('The Adventures of Sherlock Holmes', 36, 7.99, 'Mystery');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('White Fang', 37, 6.99, 'Adventure');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('The Scarlet Letter', 38, 8.99, 'Romance');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('The Three Musketeers', 39, 11.99, 'Historical Adventure');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('Oliver Twist', 40, 9.99, 'Classic');
INSERT INTO Books (title, author_id, unit_price, genres) VALUES ('A Christmas Carol', 40, 6.99, 'Classic');